networks:
  radares-net:
    external: true

services:
  # ===============================================================
  # NOSSO MICROSSERVIÇO: Radar Eixo
  # ===============================================================
  microservico-radar-eixo:
    container_name: microservico-radares-eixo
    # Em vez de 'image', usamos 'build' para construir a partir do nosso Dockerfile
    build:
      context: ../microservico-radares-eixo # Caminho relativo para a pasta do projeto
    ports:
      - "8086:8086" # Expõe a porta do serviço para a sua máquina
    environment:
      # ATIVA O PERFIL DE PRODUÇÃO, fazendo o Spring usar o application-prod.properties
      # --- Configurações do Spring ---
      - SPRING_PROFILES_ACTIVE=prod
      # --- Configurações do SFTP e Pastas ---
      - SFTP_LOCAL_DIRECTORY=/app/radar
      - SFTP_DOWNLOAD_LIMITE_DIAS=10
      - SFTP_HOST=${EIXO_SFTP_HOST}
      - SFTP_PORT=${EIXO_SFTP_PORT}
      - SFTP_USER=${EIXO_SFTP_USER}
      - SFTP_PASS=${EIXO_SFTP_PASS}
      # --- Banco de Dados ---
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # --- Mensageria (RabbitMQ) ---
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_EXCHANGE_NAME=radares_exchange
      - RABBITMQ_ROUTING_KEY=radares.eixo
    volumes:
      - "D:/Radares/Eixo:/app/radar"
    networks:
      - radares-net
    restart: on-failure
volumes:
  postgres-eixo-data:
  pgadmin-data: # <-- Adicionar o novo volume aqui
  es-data: