spring.application.name=microsservico-radar-eixo

spring.profiles.active=${APP_PROFILE:prod}
spring.jpa.open-in-view=false

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

sftp.host=${SFTP_HOST}
sftp.port=${SFTP_PORT}
sftp.user=${SFTP_USER}
sftp.pass=${SFTP_PASS}
sftp.local.directory=D:/Radares/Eixo
sftp.remote.directory=/recebidos
sftp.schedule.rate.ms=300000