server.port=8086

# Configuracoes do Actuator
management.endpoints.web.exposure.include=*
management.metrics.tags.application=microservice-radar-eixo

# ==========================================================
# ##            CONFIGURA\u00C7OO DO BANCO POSTGRESQL            ##
# ==========================================================
# Aponta para o servi\u00E7o 'postgres-db' que definiremos no Docker Compose
spring.datasource.url=jdbc:postgresql://postgres-db:5432/eixo_db
spring.datasource.username=coruja_user
spring.datasource.password=coruja_pass
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Em produ\u00E7ao real, o ideal e usar ferramentas de migra\u00E7ao como Flyway ou Liquibase
spring.jpa.hibernate.ddl-auto=update

# ==========================================================
# ##            CONFIGURA\u00C7OES DO RABBITMQ                 ##
# ==========================================================
# Aponta para o servi\u00E7o 'rabbitmq' no Docker Compose
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Producer Configuration
rabbitmq.exchange.name=radares_exchange
rabbitmq.routing.key=radares.eixo