server.port=8086

# Configur\u00E7oes do RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Producer Configuration
rabbitmq.exchange.name=radares_exchange
rabbitmq.routing.key=radares.eixo

# H2 Connection
spring.datasource.url=jdbc:h2:mem:microservico_eixo
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# H2 Client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# (O MAIS IMPORTANTE) Mostra os valores exatos dos parametros que estao sendo enviados na consulta
#logging.level.org.hibernate.orm.jdbc.bind=TRACE